#!/bin/sh
# Copyright (c) 2021, Magnus Sandberg
# BSD 2-Clause "Simplified" License

MYTAG="my-disk-prep"
SCRIPT="disk-preparation"
DLPATH="/tmp"

. /usr/share/debconf/confmodule
db_get $MYTAG/url
RC=$?
if [ $RC -eq 0 ]; then
    DLURL="$RET"
    logger -t "$MYTAG" "DLURL from preseed $MYTAG/url: $DLURL"
else
    DLURL=$( sed -n 's#.*url=\([^ ]\+/\).*#\1#p' /proc/cmdline )
    logger -t "$MYTAG" "DLURL extracted from /proc/cmdline: $DLURL"
fi
DLMETHOD=$( echo $DLURL | cut -d':' -f1 | tr 'a-z' 'A-Z' )
logger -t "$MYTAG" "DLMETHOD extracted from \$DLURL: $DLMETHOD"
if [ "x$DLMETHOD" = "xTFTP" ] ; then
    PARTS=$( echo $DLURL | sed -n 's#.*//\([^/]\+\)/\(.*\)$#\1:\2#p' )
    DLHOST=$( echo $PARTS | cut -d':' -f1 )
    logger -t "$MYTAG" "TFTP server: $DLHOST"
    DLURL=$( echo $PARTS | cut -d':' -f2 )
    logger -t "$MYTAG" "Server path: $DLURL"
    logger -t "$MYTAG" "Downloading $SCRIPT using tftp command."
    tftp -l $DLPATH/$SCRIPT -g $DLHOST -r $DLURL/$SCRIPT || exit $?
elif  [ "x$DLMETHOD" = "xPRESEED" ]; then
    logger -t "$MYTAG" "Extracting $SCRIPT from preseed data."
    # download the preseed file as the copy on disk has the comments stripped out
    db_get preseed/url
    PRESEED_URL="$RET"
    preseed_fetch "$PRESEED_URL" /tmp/preseed_raw
    cat /tmp/preseed_raw | sed -e '1,/### disk-preparation script begin/d' -e '/### disk-preparation script end/,$d' -e 's/^#\s\?//' > $DLPATH/$SCRIPT
    rm /tmp/preseed_raw
else
    logger -t "$MYTAG" "Downloading $SCRIPT using wget command."
    wget -P $DLPATH/ $DLURL/$SCRIPT || exit $?
fi
logger -t "$MYTAG" "Starting $SCRIPT"
chmod +x $DLPATH/$SCRIPT && $DLPATH/$SCRIPT
RC=$?
if [ $RC -eq 0 ]; then
    logger -t "$MYTAG" "$SCRIPT finished OK."
else
    logger -t "$MYTAG" "Disk preparation failed."
    exit $RC
fi
